global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "resume-parser"
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: https
    static_configs:
      - targets: ["api.hirevox.ai:443"]
