global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9091"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3101"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3201"]
